/*
 * Name: lptmr.h
 * Author: Martin Stankus
 *
 */

#ifndef _LPTMR_H_
#define _LPTMR_H_

#define LPTMR_CSR_TPS_VAL_CMP0_LPTMR0		0
#define LPTMR_CSR_TPS_VAL_ALT1				1
#define LPTMR_CSR_TPS_VAL_ALT2				2
#define LPTMR_CSR_TPS_VAL_ALT3				3

#define LPTMR_PSR_PRS_VAL_DIV2				0
#define LPTMR_PSR_PRS_VAL_DIV4_EDG2			1
#define LPTMR_PSR_PRS_VAL_DIV8_EDG4			2
#define LPTMR_PSR_PRS_VAL_DIV16_EDG8		3
#define LPTMR_PSR_PRS_VAL_DIV32_EDG16		4
#define LPTMR_PSR_PRS_VAL_DIV64_EDG32		5
#define LPTMR_PSR_PRS_VAL_DIV128_EDG64		6
#define LPTMR_PSR_PRS_VAL_DIV256_EDG128		7
#define LPTMR_PSR_PRS_VAL_DIV512_EDG256		8
#define LPTMR_PSR_PRS_VAL_DIV1K_EDG512		9
#define LPTMR_PSR_PRS_VAL_DIV2K_EDG1K		10
#define LPTMR_PSR_PRS_VAL_DIV4K_EDG2K		11
#define LPTMR_PSR_PRS_VAL_DIV8K_EDG4K		12
#define LPTMR_PSR_PRS_VAL_DIV16K_EDG8K		13
#define LPTMR_PSR_PRS_VAL_DIV32K_EDG16K		14
#define LPTMR_PSR_PRS_VAL_DIV64K_EDG32K		15

#define LPTMR_PSR_PCS_VAL_SIRCCLK			0
#define LPTMR_PSR_PCS_VAL_LPOCLK			1
#define LPTMR_PSR_PCS_VAL_OSC32KCLK			2
#define LPTMR_PSR_PCS_VAL_ERCLK				3

#endif /* _LPTMR_H_ */
