/*
 * board.c
 *
 *  Created on: 10. 3. 2018
 *      Author: mirek
 */

#include "board.h"

/* var */

static const uint32_t MCULED[4] = {IOIND_MCU_LED1, IOIND_MCU_LED2, IOIND_MCU_LED3, IOIND_MCU_LED4};
static const uint32_t MCUBTN[4] = {IOIND_MCU_BTN1, IOIND_MCU_BTN2, IOIND_MCU_BTN3, IOIND_MCU_BTN4};

/* proto */
static void board_MCULED_Init(void);
static void board_MCUBTN_Init(void);
static void board_MCUSW_Init(void);
static void board_WIFI_Init(void);

/* fcns */

void Board_Init(void)
{
	/* hodiny */
	PCC_PORTB = PCC_CLKCFG_CGC_MASK;
	PCC_PORTD = PCC_CLKCFG_CGC_MASK;

	board_MCULED_Init();
	board_MCUBTN_Init();
	board_MCUSW_Init();

	board_WIFI_Init();

}

void Board_MCULED_Set(uint8_t led, bool value)
{
	led--;
	GPIO_MCU_LEDS->PDOR = (((uint32_t)GPIO_MCU_LEDS->PDOR) & ~(1u << MCULED[led])) | (((uint32_t)value) << MCULED[led]);
}

bool Board_MCUBTN_Get(uint8_t btn)
{
	btn--;
	return !((bool)((GPIO_MCU_BTNS->PDIR & (1u << MCUBTN[btn])) >> MCUBTN[btn]));
}


void board_WIFI_Init(void)
{
	PORT_WIFI->PCR[IOIND_WIFI_EN] = PORT_PCR_MUX(PORT_PCR_MUX_VAL_GPIO);
	PORT_WIFI->PCR[IOIND_WIFI_RX] = PORT_PCR_MUX(PORT_PCR_MUX_VAL_ALT3);
	PORT_WIFI->PCR[IOIND_WIFI_TX] = PORT_PCR_MUX(PORT_PCR_MUX_VAL_ALT3);
	PORT_WIFI->PCR[IOIND_WIFI_RESET] = PORT_PCR_MUX(PORT_PCR_MUX_VAL_GPIO);
	PORT_WIFI->PCR[IOIND_WIFI_WAKE] = PORT_PCR_MUX(PORT_PCR_MUX_VAL_GPIO);
	PORT_WIFI->PCR[IOIND_WIFI_IO] = PORT_PCR_MUX(PORT_PCR_MUX_VAL_GPIO);

	GPIO_WIFI->PDDR |= (1u << IOIND_WIFI_EN);
	GPIO_WIFI->PDDR |= (1u << IOIND_WIFI_RESET);
	GPIO_WIFI->PDDR |= (1u << IOIND_WIFI_WAKE);
	GPIO_WIFI->PDDR &= ~(1u << IOIND_WIFI_IO);

	GPIO_WIFI->PCOR = (1u << IOIND_WIFI_EN);
	GPIO_WIFI->PSOR = (1u << IOIND_WIFI_RESET);

	PCC_INTMUX0 = PCC_CLKCFG_CGC_MASK;
	INTMUX0->CHANNEL->CHn_IER_31_0 = INTMUX_LPUART2_MASK;
	NVIC_SetPriority(INTMUX0_0_IRQn, 2);
	NVIC_EnableIRQ(INTMUX0_0_IRQn);
}

void board_MCULED_Init(void)
{
	/*Nastaveni PORTu a GPIO pro LEDky*/
	PORT_MCU_LEDS->PCR[IOIND_MCU_LED1] = PORT_PCR_MUX(PORT_PCR_MUX_VAL_GPIO);
	PORT_MCU_LEDS->PCR[IOIND_MCU_LED2] = PORT_PCR_MUX(PORT_PCR_MUX_VAL_GPIO);
	PORT_MCU_LEDS->PCR[IOIND_MCU_LED3] = PORT_PCR_MUX(PORT_PCR_MUX_VAL_GPIO);
	PORT_MCU_LEDS->PCR[IOIND_MCU_LED4] = PORT_PCR_MUX(PORT_PCR_MUX_VAL_GPIO);

	GPIO_MCU_LEDS->PDDR |= MCU_LEDS_MASK;
}

void board_MCUBTN_Init(void)
{
	/*Nastaveni PORTu a GPIO pro tlacitka*/
	PORT_MCU_BTNS->PCR[IOIND_MCU_BTN1] = PORT_PCR_MUX(PORT_PCR_MUX_VAL_GPIO) | PORT_PCR_PE_MASK | PORT_PCR_PS_MASK;
	PORT_MCU_BTNS->PCR[IOIND_MCU_BTN2] = PORT_PCR_MUX(PORT_PCR_MUX_VAL_GPIO) | PORT_PCR_PE_MASK | PORT_PCR_PS_MASK;
	PORT_MCU_BTNS->PCR[IOIND_MCU_BTN3] = PORT_PCR_MUX(PORT_PCR_MUX_VAL_GPIO) | PORT_PCR_PE_MASK | PORT_PCR_PS_MASK;
	PORT_MCU_BTNS->PCR[IOIND_MCU_BTN4] = PORT_PCR_MUX(PORT_PCR_MUX_VAL_GPIO) | PORT_PCR_PE_MASK | PORT_PCR_PS_MASK;

	GPIO_MCU_LEDS->PDDR &= ~MCU_BTNS_MASK;
}

void board_MCUSW_Init(void)
{
	PORT_MCU_SW->PCR[IOIND_MCU_SW1] = PORT_PCR_MUX(PORT_PCR_MUX_VAL_GPIO) | PORT_PCR_PE_MASK | PORT_PCR_PS_MASK;
	PORT_MCU_SW->PCR[IOIND_MCU_SW2] = PORT_PCR_MUX(PORT_PCR_MUX_VAL_GPIO) | PORT_PCR_PE_MASK | PORT_PCR_PS_MASK;
	PORT_MCU_SW->PCR[IOIND_MCU_SW3] = PORT_PCR_MUX(PORT_PCR_MUX_VAL_GPIO) | PORT_PCR_PE_MASK | PORT_PCR_PS_MASK;
	PORT_MCU_SW->PCR[IOIND_MCU_SW4] = PORT_PCR_MUX(PORT_PCR_MUX_VAL_GPIO) | PORT_PCR_PE_MASK | PORT_PCR_PS_MASK;

	GPIO_MCU_SW->PDDR &= ~MCU_SWS_MASK;
}
