/*
 * Name: frdm-kl28z_demo2.c
 * Author: Martin Stankus
 *
 */

#include "MKL28Z7.h"
#include "wdog.h"
#include "clkout.h"
#include "io_frdm.h"
#include "intmux.h"
#include "port.h"
#include "adc.h"
#include "pcc.h"
#include "lptmr.h"

#define LSENS_ADC_IRQ_PRI			1
#define LSENS_ADC_REGSET			0
#define LSENS_MEAS_PERIOD			512u

#define DATA_SAMP_PERIOD			32768u

void __attribute__ ((interrupt)) ADC0_IRQHandler(void)
{
	uint8_t val;

	val = ADC0->R[LSENS_ADC_REGSET];
	if (val > 230ul) {
		GPIO_LEDG->PSOR = IOMASK_LEDG;
	} else {
		GPIO_LEDG->PCOR = IOMASK_LEDG;
	}
}

void __attribute__ ((interrupt)) LPTMR1_IRQHandler(void)
{
	LPTMR1->CSR = LPTMR_CSR_TCF_MASK | LPTMR_CSR_TIE_MASK | LPTMR_CSR_TEN_MASK;
}

void __attribute__ ((interrupt)) LPSPI2_IRQHandler(void)
{
}

void __attribute__ ((interrupt)) LPUART2_IRQHandler(void)
{
}

void demo_pcc_init(void)
{
	PCC_ADC0 = PCC_CLKCFG_CGC_MASK | PCC_CLKCFG_PCS(PCC_CKFG_PCS_VAL_DIS);
	PCC_LPTMR0 = PCC_CLKCFG_CGC_MASK;
	PCC_LPTMR1 = PCC_CLKCFG_CGC_MASK;
	PCC_LPSPI2 = PCC_CLKCFG_CGC_MASK | PCC_CLKCFG_PCS(PCC_CKFG_PCS_VAL_FIRCLK);
	PCC_LPUART2 = PCC_CLKCFG_CGC_MASK | PCC_CLKCFG_PCS(PCC_CKFG_PCS_VAL_FIRCLK);
	PCC_INTMUX0 = PCC_CLKCFG_CGC_MASK;
	PCC_PORTB = PCC_CLKCFG_CGC_MASK;
	PCC_PORTC = PCC_CLKCFG_CGC_MASK;
	PCC_PORTD = PCC_CLKCFG_CGC_MASK;
}

void demo_port_init(void)
{
	PORT_LPSPI2_PCS0->PCR[IOIND_LPSPI2_PCS0] = PORT_PCR_MUX(PORT_PCR_MUX_VAL_ALT2);
	PORT_LPSPI2_SCK->PCR[IOIND_LPSPI2_SCK] = PORT_PCR_MUX(PORT_PCR_MUX_VAL_ALT2);
	PORT_LPSPI2_SOUT->PCR[IOIND_LPSPI2_SOUT] = PORT_PCR_MUX(PORT_PCR_MUX_VAL_ALT2);
	PORT_LPSPI2_SIN->PCR[IOIND_LPSPI2_SIN] = PORT_PCR_MUX(PORT_PCR_MUX_VAL_ALT2);

	PORT_LPUART2_RTS->PCR[IOIND_LPUART2_RTS] = PORT_PCR_MUX(PORT_PCR_MUX_VAL_ALT3);
	PORT_LPUART2_CTS->PCR[IOIND_LPUART2_CTS] = PORT_PCR_MUX(PORT_PCR_MUX_VAL_ALT3);
	PORT_LPUART2_RX->PCR[IOIND_LPUART2_RX] = PORT_PCR_MUX(PORT_PCR_MUX_VAL_ALT3);
	PORT_LPUART2_TX->PCR[IOIND_LPUART2_TX] = PORT_PCR_MUX(PORT_PCR_MUX_VAL_ALT3);

	PORT_LEDG->PCR[IOIND_LEDG] = PORT_PCR_MUX(PORT_PCR_MUX_VAL_GPIO);
}

void demo_lsens_init(void)
{
	LPTMR0->CSR = 0;

	TRGMUX_ADC0 = TRGMUX_TRGCFG_SEL0(kTRGMUX_SourceLptmr0Trg);

	ADC0->CFG1 = ADC_CFG1_ADLSMP_MASK | ADC_CFG1_ADICLK(ADC_CFG1_ICLK_VAL_ADACK);
	ADC0->CFG2 = ADC_MUX_LSENS;
	ADC0->SC2 = ADC_SC2_ADTRG_MASK;
	ADC0->SC1[LSENS_ADC_REGSET] = ADC_SC1_AIEN_MASK | ADC_SC1_ADCH(ADC_CHAN_LSENS);

	NVIC_SetPriority(ADC0_IRQn, LSENS_ADC_IRQ_PRI);
	NVIC_EnableIRQ(ADC0_IRQn);

	GPIO_LEDG->PDDR |= IOMASK_LEDG;

	LPTMR0->PSR = LPTMR_PSR_PBYP_MASK | LPTMR_PSR_PCS(LPTMR_PSR_PCS_VAL_OSC32KCLK);
	LPTMR0->CMR = LSENS_MEAS_PERIOD - 1;
	LPTMR0->CSR = LPTMR_CSR_TEN_MASK;
}

int main(void)
{
	wdog_set(WDOG_CONF_LPOCLK_PRESC_OFF, 1000);
	clkout_set(CLKOUT_CONF_SOSCCLK);

	demo_pcc_init();
	demo_port_init();

	demo_lsens_init();

	/*
	LPTMR1->CSR = 0;

	INTMUX0->CHANNEL[2].CHn_IER_31_0 = INTMUX_SRC_LPTMR1;

	NVIC_SetPriority(INTMUX0_2_IRQn, 2);
	NVIC_EnableIRQ(INTMUX0_2_IRQn);

	LPTMR1->PSR = LPTMR_PSR_PRESCALE(4) | LPTMR_PSR_PCS(2);
	LPTMR1->CMR = LPTMR1_MOD - 1;
	LPTMR1->CSR = LPTMR_CSR_TIE_MASK | LPTMR_CSR_TEN_MASK;
	*/

	while (1) {
		wdog_refresh();
	}

	return 0;
}
