/*
 * Name: frdm-kl28z_demo1.c
 * Author: Martin Stankus
 *
 */

#include "MKL28Z7.h"
#include "wdog.h"
#include "clkout.h"
#include "io_frdm.h"
#include "intmux.h"
#include "port.h"
#include "adc.h"
#include "pcc.h"
#include "lptmr.h"

#define LSENS_ADC_IRQ_PRI			1
#define LSENS_ADC_REGSET			0
#define LSENS_MEAS_PERIOD			512u

#define DMA_CHN_LPUART2_TX			0

void __attribute__ ((interrupt)) ADC0_IRQHandler(void)
{
	uint8_t val;

	val = ADC0->R[LSENS_ADC_REGSET];
	if (val > 230ul) {
		GPIO_LEDG->PSOR = IOMASK_LEDG;
	} else {
		GPIO_LEDG->PCOR = IOMASK_LEDG;
	}
}

void __attribute__ ((interrupt)) LPUART2_IRQHandler(void)
{
}

void __attribute__ ((interrupt)) DMA0_04_IRQHandler(void)
{
	DMA0->CINT = DMA_CHN_LPUART2_TX;
}

void demo_pcc_init(void)
{
	PCC_ADC0 = PCC_CLKCFG_CGC_MASK | PCC_CLKCFG_PCS(PCC_CKFG_PCS_VAL_DIS);
	PCC_LPTMR0 = PCC_CLKCFG_CGC_MASK;
	PCC_LPUART2 = PCC_CLKCFG_CGC_MASK | PCC_CLKCFG_PCS(PCC_CKFG_PCS_VAL_FIRCLK);
	PCC_INTMUX0 = PCC_CLKCFG_CGC_MASK;
	PCC_DMAMUX0 = PCC_CLKCFG_CGC_MASK;
	PCC_DMA0 = PCC_CLKCFG_CGC_MASK;
	PCC_PORTC = PCC_CLKCFG_CGC_MASK;
	PCC_PORTD = PCC_CLKCFG_CGC_MASK;
}

void demo_port_init(void)
{
	PORT_LPUART2_RTS->PCR[IOIND_LPUART2_RTS] = PORT_PCR_MUX(PORT_PCR_MUX_VAL_ALT3);
	PORT_LPUART2_CTS->PCR[IOIND_LPUART2_CTS] = PORT_PCR_MUX(PORT_PCR_MUX_VAL_ALT3);
	PORT_LPUART2_RX->PCR[IOIND_LPUART2_RX] = PORT_PCR_MUX(PORT_PCR_MUX_VAL_ALT3);
	PORT_LPUART2_TX->PCR[IOIND_LPUART2_TX] = PORT_PCR_MUX(PORT_PCR_MUX_VAL_ALT3);

	PORT_LEDG->PCR[IOIND_LEDG] = PORT_PCR_MUX(PORT_PCR_MUX_VAL_GPIO);
}

void demo_lsens_init(void)
{
	LPTMR0->CSR = 0;

	TRGMUX_ADC0 = TRGMUX_TRGCFG_SEL0(kTRGMUX_SourceLptmr0Trg);

	ADC0->CFG1 = ADC_CFG1_ADLSMP_MASK | ADC_CFG1_ADICLK(ADC_CFG1_ICLK_VAL_ADACK);
	ADC0->CFG2 = ADC_MUX_LSENS;
	ADC0->SC2 = ADC_SC2_ADTRG_MASK;
	ADC0->SC1[LSENS_ADC_REGSET] = ADC_SC1_AIEN_MASK | ADC_SC1_ADCH(ADC_CHAN_LSENS);

	NVIC_SetPriority(ADC0_IRQn, LSENS_ADC_IRQ_PRI);
	NVIC_EnableIRQ(ADC0_IRQn);

	GPIO_LEDG->PDDR |= IOMASK_LEDG;

	LPTMR0->PSR = LPTMR_PSR_PBYP_MASK | LPTMR_PSR_PCS(LPTMR_PSR_PCS_VAL_OSC32KCLK);
	LPTMR0->CMR = LSENS_MEAS_PERIOD - 1;
	LPTMR0->CSR = LPTMR_CSR_TEN_MASK;
}

int main(void)
{
	wdog_set(WDOG_CONF_LPOCLK_PRESC_OFF, 1000);
	clkout_set(CLKOUT_CONF_SOSCCLK);

	LPUART2->WATER = LPUART_WATER_RXWATER(1) | LPUART_WATER_TXWATER(3);
	LPUART2->FIFO = LPUART_FIFO_TXFE_MASK | LPUART_FIFO_RXFE_MASK;
	LPUART2->MODIR = LPUART_MODIR_RTSWATER(2) | LPUART_MODIR_RXRTSE_MASK | LPUART_MODIR_TXCTSE_MASK;
	LPUART2->CTRL = LPUART_CTRL_RIE_MASK | LPUART_CTRL_TE_MASK | LPUART_CTRL_RE_MASK;
	LPUART2->BAUD = LPUART_BAUD_OSR(15) | LPUART_BAUD_TDMAE_MASK | LPUART_BAUD_SBR(26);

	DMAMUX0->CHCFG[0] = DMAMUX_CHCFG_ENBL_MASK | DMAMUX_CHCFG_SOURCE(kDmaRequestMux0LPUART2Tx);

	DMA0->CR = DMA_CR_EDBG_MASK;
	DMA0->SERQ = DMA_CHN_LPUART2_TX;

	//DMA0->TCD[DMA_CHN_LPUART2_TX].SADDR;

	demo_pcc_init();
	demo_port_init();

	demo_lsens_init();

	while (1) {
		wdog_refresh();
	}

	return 0;
}
