/*
 * Name: system_MKL28Z7.c
 * Author: Martin Stankus
 *
 */

#include "MKL28Z7.h"

volatile uint32_t SystemCoreClock = DEFAULT_SYSTEM_CLOCK;

void SystemInit(void)
{
	WDOG0->TOVAL = WDOG_TOVAL_VAL_BOOT;
	WDOG0->CS = WDOG_CS_CMD32EN_MASK | WDOG_CS_PRES_VAL_BOOT | WDOG_CS_CLK_VAL_BOOT |
				WDOG_CS_EN_MASK | WDOG_CS_UPDATE_MASK;

	SCG->SOSCDIV = SCG_SOSCDIV_DIV3_VAL | SCG_SOSCDIV_DIV1_VAL;
	SCG->SOSCCFG = SCG_SOSCCFG_SCXP_VAL | SCG_SOSCCFG_RANGE_VAL | SCG_SOSCCFG_EREFS_MASK;
	SCG->SOSCCSR = SCG_SOSCCSR_SOSCERCLKEN_MASK |
					SCG_SOSCCSR_SOSCLPEN_MASK |
					SCG_SOSCCSR_SOSCSTEN_MASK	 |
					SCG_SOSCCSR_SOSCEN_MASK;
	while (!(SCG->SOSCCSR & SCG_SOSCCSR_SOSCVLD_MASK));


	SCG->FIRCDIV = SCG_FIRCDIV_DIV3_VAL | SCG_FIRCDIV_DIV1_VAL;
	SCG->FIRCCFG = SCG_FIRCCFG_RANGE_VAL;
	SCG->FIRCCSR = SCG_FIRCCSR_FIRCLPEN_MASK |
					SCG_FIRCCSR_FIRCSTEN_MASK |
					SCG_FIRCCSR_FIRCEN_MASK;
	while (!(SCG->FIRCCSR & SCG_FIRCCSR_FIRCVLD_MASK));

	SCG->SPLLDIV = SCG_SPLLDIV_DIV3_VAL | SCG_SPLLDIV_DIV1_VAL;
	SCG->SPLLCFG = SCG_SPLLCFG_MULT_VAL | SCG_SPLLCFG_PREDIV_VAL | SCG_SPLLCFG_SOURCE_MASK;
	SCG->SPLLCSR = SCG_SPLLCSR_SPLLERR_MASK |
					SCG_SPLLCSR_SPLLCMRE_MASK |
					SCG_SPLLCSR_SPLLCM_MASK |
					SCG_SPLLCSR_SPLLSTEN_MASK |
					SCG_SPLLCSR_SPLLEN_MASK;
	while (!(SCG->SPLLCSR & SCG_SPLLCSR_SPLLVLD_MASK));
	//0300 0001
	SCG->RCCR = SCG_CCRCSR_SCS_VAL_SPLL | SCG_CCRCSR_DIVCORE_RUN_VAL | SCG_CCRCSR_DIVSLOW_RUN_VAL;
	while ((SCG->CSR & SCG_CSR_SCS_MASK) != SCG_CCRCSR_SCS_VAL_SPLL );

	SCG->SIRCCSR = 0;
	while (SCG->SIRCCSR & SCG_SIRCCSR_SIRCVLD_MASK);
	SCG->SIRCDIV = SCG_SIRCDIV_DIV3_VAL | SCG_SIRCDIV_DIV1_VAL;
	SCG->SIRCCFG = SCG_SIRCCFG_RANGE_VAL;
	SCG->SIRCCSR = SCG_SIRCCSR_SIRCLPEN_MASK |
					SCG_SIRCCSR_SIRCSTEN_MASK |
					SCG_SIRCCSR_SIRCEN_MASK;
	while (!(SCG->SIRCCSR & SCG_SIRCCSR_SIRCVLD_MASK));

	SCG->VCCR = SCG_CCRCSR_SCS_VAL_SIRC | SCG_CCRCSR_DIVCORE_VLPR_VAL | SCG_CCRCSR_DIVSLOW_VLPR_VAL;
}

void SystemCoreClockUpdate(void)
{
	uint32_t SCGOUTClock;                                 /* Variable to store output clock frequency of the SCG module */
	  uint16_t Divider, prediv, multi;
	  Divider = ((SCG->CSR & SCG_CSR_DIVCORE_MASK) >> SCG_CSR_DIVCORE_SHIFT) + 1;

	  switch ((SCG->CSR & SCG_CSR_SCS_MASK) >> SCG_CSR_SCS_SHIFT) {
	    case 0x1:
	      /* System OSC */
	      SCGOUTClock = CPU_INT_SLOW_CLK_HZ;
	      break;
	    case 0x2:
	      /* Slow IRC */
	      SCGOUTClock = (((SCG->SIRCCFG & SCG_SIRCCFG_RANGE_MASK) >> SCG_SIRCCFG_RANGE_SHIFT) ? 8000000 : 2000000);
	      break;
	    case 0x3:
	      /* Fast IRC */
	      SCGOUTClock = 48000000 + ((SCG->FIRCCFG & SCG_FIRCCFG_RANGE_MASK) >> SCG_FIRCCFG_RANGE_SHIFT) * 4000000;
	      break;
	    case 0x6:
	      /* System PLL */
	      if ((SCG->SPLLCFG & SCG_SPLLCFG_SOURCE_MASK) >> SCG_SPLLCFG_SOURCE_SHIFT) {
	        SCGOUTClock = 48000000 + ((SCG->FIRCCFG & SCG_FIRCCFG_RANGE_MASK) >> SCG_FIRCCFG_RANGE_SHIFT) * 4000000;
	      }
	      else {
	        SCGOUTClock = CPU_INT_SLOW_CLK_HZ;
	      }
	      prediv = ((SCG->SPLLCFG & SCG_SPLLCFG_PREDIV_MASK) >> SCG_SPLLCFG_PREDIV_SHIFT) + 1;
	      multi = ((SCG->SPLLCFG & SCG_SPLLCFG_MULT_MASK) >> SCG_SPLLCFG_MULT_SHIFT) + 16;
	      SCGOUTClock = SCGOUTClock * multi / (prediv * 2);
	      break;
	    default:
	      return;
	  }

	  SystemCoreClock = (SCGOUTClock / Divider);
}
